### ISSUE TITLE
What is the GPU implementation in the evaluation?

### ISSUE THREAD

**Issue by coach-wang** [LIAGM/LFattNet#12]
Hi, the LFattNet is interseting. However, it is reported out of memory when I test the network using the 512x512 HCI light field data (with a 2080ti GPU). I am wandering that how to use a single 1080ti GPU to test the network as the your paper, thanks!

**Comment by LIAGM** [comment]
Hi,

We only test that environment and the setting is for only one program running on GPU.
The memory usage is enough for the environment setting.
If you run other programs in the same time the OOM problem may occur.

**Comment by coach-wang** [comment]
> Hi,
> 
> We only test that environment and the setting is for only one program running on GPU. The memory usage is enough for the environment setting. If you run other programs in the same time the OOM problem may occur.

I found that I forgot to stop other programs before, and the OOM problem is solved  after killing other progress. Thank you!
