### ISSUE TITLE
Out of Memory? what's the problem?

### ISSUE THREAD

**Issue by dreamhua82** [LIAGM/LFattNet#3]
Dear Liang,
My test PC is like this: one NVIDIA GTX 1080Ti GPU, CPU: intel i5, Memory: 8GB
but when I run it , it show : GPU out of memory. 
Regards,

**Comment by LIAGM** [comment]
Hi

Could you provide more information of your test PC?
If you fit the environment which I describe, this should not be a problem.
Thanks

Best Regards,

**Comment by huaxiyao** [comment]
I installed the package as you stated, my software environment  is Win 7, anaconda, TF, keras , the version is the same to you, and the code can run to all image loaded.  but when it load the LFatt model, it shows GPU out of memory.
I guess,  Maybe  the CNN model it too large? 81 sub-nets and 3D CNN regression ?
Can you give me any advice about it, I need to train it for study.
Many thanks for your reply.

**Comment by LIAGM** [comment]
Hi

For this situation, the main problem may be the OS.
I also encounter this problem when I use Win10 for training and testing my network with 1080ti.
Our model use almost all memory in 1080ti, but Windows system will remain some space not to be used.
So the advice I can give to you is to use Ubuntu to be your OS and build the same environment as I described.
Sorry for this problem

Best Regards,

**Comment by dreamhua82** [comment]
Dear LIAGM,
I have changed the os to Ubuntu 18.04, the code can run to the "Epoch: 1/1" ,but stop there and can't run any more.
My GPU is 1080TI,  memory is 8GB. May be the memory is not enough?
What do you think about it?
Thanks.

**Comment by LIAGM** [comment]
Hi

I did not test my code in Ubuntu 18.04.
So I do not know the problem now is the OS difference between 16.04 and 18.04 or the lack of memory.
I think the first step is to change the environment as my setting.
And you can check the problem is from OS difference or the memory.
Thanks

Best Regards,

**Comment by dreamhua82** [comment]
Hi, I am very sorry for trouble you so much.
Have you ever use pytorch to train your model? I just slightly modify the code using pytorch. but the result seems not good as in keras version. I doubt the order of dataset loader( especially for EPI) is wrong in my code. (i.e. [B,C,H,W] in pytorch's tensor;  ). Do you have this experience? or give me some advice. Thansk a lot.
