### ISSUE TITLE
How to imlement  operation?

### ISSUE THREAD

**Issue by dreamhua82** [LIAGM/LFattNet#4]
Dear LIAGM,
Can the code below implement the operation? is it right ? I use this in the program, but find the Cost volume became Nan ! 

Thanks

**Comment by LIAGM** [comment]
Hi

I just wonder why you want to use correlation in the costvolume?
And as I remembered, this part of the code is to construct the costvolume.
The tmp_list contains N*N shifted feature map, and I am not sure what you want to correlate with?
Can you describe more clearly for the output of the function?

Regards,

**Comment by dreamhua82** [comment]
Dear LIAGM, 
As used in stereo matching, similar to use concatemation to construct cost volume(4D cost volume, B D H W C), correlation is using inner product (3D cost volume) .So, I use this code: cost = multiply(tmp_list)  # dot product [B, H, W, C]. but the cost volume become 0.
The obove function is to construct 3D cost volume(not including channel dimension) (B D H W) .Any help?
Thanks,

**Comment by LIAGM** [comment]
Hi 

I am not sure that the function of multiply can do the operation you want.
Maybe you can simply do some correlation operation in the channel dimension separately to make it become a scalar.
These are the suggestion I can give to you

Regards,
