### ISSUE TITLE
How to resolve this?

### ISSUE THREAD

**Issue by Vishwanathts01** [LIAGM/LFattNet#8]
num_samples = int(nest.flatten(data)[0].shape[0])
AttributeError: 'threadsafe_iter' object has no attribute 'shape'

**Comment by sherlockholmes211** [comment]
Hi, I also got the same error, have you resolved it now?

**Comment by sherlockholmes211** [comment]
> num_samples = int(nest.flatten(data)[0].shape[0]) AttributeError: 'threadsafe_iter' object has no attribute 'shape'
Hi, I also got the same error, have you resolved it now?

**Comment by chaowentao** [comment]
I fixed the problem. downgrade the tensorflow-gpu=1.10. You can try it.
```
conda install tensorflow-gpu=1.10
```
